modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="lgstones"
version="0.1.0"
displayName="Legends of the Stones"
displayURL=""
logoFile=""
credits="Created by Auranite Studio"
authors=""
description=""

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
config = "lgstones.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.lgstones]]
modId="neoforge"
type="required"
versionRange="[21.1.215,)"
ordering="AFTER"
side="BOTH"

[[dependencies.lgstones]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration